version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  rebase-strategy: "disabled"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: html-proofer
  - dependency-name: rubocop
- package-ecosystem: "npm"
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  rebase-strategy: "disabled"
  open-pull-requests-limit: 10
