version: 2

jobs:
  build:
    working_directory: ~/folkingebrew
    docker:
      - image: circleci/ruby:2.4.3
    steps:
      - checkout

      - restore_cache:
          key: middleman-project-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: middleman-project-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - run:
          name: Setup the environment
          command: cp .env.sample .env

      - run:
          name: Build Folkingebrew site
          command: bundle exec rake build
