version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.1-node

    steps:
      - checkout

      - restore_cache:
          key: middleman-project-{{ arch }}-{{ checksum "Gemfile.lock" }}

      - run:
          name: Install Ruby dependencies
          command: bundle install --path vendor/bundle

      - save_cache:
          key: middleman-project-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      - restore_cache: 
          key: middleman-project-{{ arch }}-{{ checksum "yarn.lock" }}

      - run: 
          name: Install Yarn packages
          command: yarn install --immutable

      - save_cache: 
          key: middleman-project-{{ arch }}-{{ checksum "yarn.lock"}}
          paths: 
            - .yarn/cache
            - .yarn/unplugged

      - run:
          name: Setup the environment
          command: cp .env.sample .env

      - run:
          name: Run the default tasks
          command: bundle exec rake default
